### ISSUE TITLE
Allow filtering of GitHub Link field against wildcards

### ISSUE THREAD

**Issue by NyanKiyoshi** [mirumee/github-jira-integrator#3]
Hi,

In JQL, I would like to be able to use the `GitHub Link` field as a `TEXT` field to perform custom filtering, e.g. only selecting _backend_ issues.

For example:
```
project = CORE AND "GitHub Link" ~ "/saleor/*" ORDER BY Rank ASC
```

> The operator '~' is not supported by the 'GitHub Link' field.

What could we do allow such wildcard filtering?

**Comment by mociepka** [comment]
I wasn't aware of those limitations when I was adding this field. The problem now is that we can't just change field type in JIRA. We can create new one migrate all content to it and remove old one.

If you have time for that @Mowinski I added another "GitHub Link" field (Text Field). If you change the script we can use a new one.

**Comment by maarcingebala** [comment]
We do have this TEXT field for `GitHub Link` now, but `GitHub Link` is also used by our scripts to match tickets from Github by link. Unfortunately it is not possible to do the "exact" search using `~` operator and this is the only operator allowed for text fields. There is even an open issue on Jira Server for that: https://jira.atlassian.com/browse/JRASERVER-21372

I will migrate all Jira issues to the previous Github Link field that was of URL type. If we want to have tha ability to filter by repository, I would suggest introducing a separate field for that.

**Comment by maarcingebala** [comment]
Problem with `~` is that it may return more than one tickets. E.g if we have two Jira issues and they have those links:

- https://github.com/mirumee/saleor/issues/ABC
- https://github.com/mirumee/saleor-dashboard/issues/ABC

A query to match the first one would be:

```
GitHub Link ~ "\"https://github.com/mirumee/saleor/issues/ABC\""
```

And it also returns the second one.

**Comment by NyanKiyoshi** [comment]
My need was to be able to filter out frontend issues from backend 😄

**Comment by NyanKiyoshi** [comment]
But I believe somebody fixed it a while ago. But they told me we need to re-sync to change the field. I don't remember who, so I cannot find the message anymore. But I was told in private it is possible to achieve it.

**Comment by maarcingebala** [comment]
`Github Link` field needs to be a URL field for the reasons I mentioned above. If you want to have a text field to filter issues by repo, we need second field for that.
